'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Check, ChevronDown, ChevronUp, Edit3, Film, Image as ImageIcon, Plus, Power, Save, Trash2, X } from 'lucide-react';
import { api } from '@/lib/api';
import { useParams } from 'next/navigation';

type Step = { title: string; content: string; mediaType: 'image' | 'video' | null; mediaUrl: string | null; requiresInput: boolean; inputKey: string | null; inputLabel: string | null };
type Guide = { id: string; title: string; description: string | null; active: boolean; steps: Step[] } | null;
type Product = { id: string; serviceId: string; title: string; description: string; price: string; currency: string; icon: string; active: boolean; requiresGuide: boolean };
const input = 'w-full rounded-2xl border border-white/10 bg-white/[0.045] px-4 py-3 text-sm text-white outline-none placeholder:text-white/25 focus:border-cyan-400/50';
const blankStep = (): Step => ({ title: '', content: '', mediaType: null, mediaUrl: null, requiresInput: false, inputKey: null, inputLabel: null });

export default function ProductsPage() {
  const { serviceId } = useParams<{ serviceId: string }>();
  const [products, setProducts] = useState<Product[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const [serviceTitle, setServiceTitle] = useState('محصولات سرویس'), [editing, setEditing] = useState<Product | null>(null), [productOpen, setProductOpen] = useState(false), [guideOpen, setGuideOpen] = useState(false);
  const [form, setForm] = useState({ title: '', description: '', price: '', currency: 'IRT', icon: 'box', active: true, requiresGuide: true });
  const [guide, setGuide] = useState<Guide>(null), [guideTitle, setGuideTitle] = useState(''), [guideDescription, setGuideDescription] = useState(''), [steps, setSteps] = useState<Step[]>([]), [saving, setSaving] = useState(false);

  async function load() { setLoading(true); try { const [p, s] = await Promise.all([api<Product[]>(`admin/services/${serviceId}/products`), api<any>(`admin/services/${serviceId}`)]); setProducts(p); setServiceTitle(s.title); } catch (e) { setError(e instanceof Error ? e.message : 'خطا در دریافت اطلاعات'); } finally { setLoading(false); } }
  useEffect(() => { if (serviceId) void load(); }, [serviceId]);

  function createProduct() { setEditing(null); setForm({ title: '', description: '', price: '', currency: 'IRT', icon: 'box', active: true, requiresGuide: true }); setProductOpen(true); }
  function editProduct(p: Product) { setEditing(p); setForm({ title: p.title, description: p.description, price: p.price, currency: p.currency, icon: p.icon, active: p.active, requiresGuide: p.requiresGuide }); setProductOpen(true); }
  async function saveProduct() { setSaving(true); setError(''); try { const body = { ...form, serviceId }; const saved = editing ? await api<Product>(`admin/products/${editing.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }) : await api<Product>('admin/products', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); setProducts(x => editing ? x.map(p => p.id === saved.id ? saved : p) : [...x, saved]); setProductOpen(false); } catch (e) { setError(e instanceof Error ? e.message : 'ذخیره محصول ناموفق بود.'); } finally { setSaving(false); } }
  async function toggle(p: Product) { try { const saved = await api<Product>(`admin/products/${p.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ active: !p.active }) }); setProducts(x => x.map(i => i.id === saved.id ? saved : i)); } catch (e) { setError(e instanceof Error ? e.message : 'خطا'); } }
  async function remove(p: Product) { if (!confirm(`محصول «${p.title}» غیرفعال شود؟`)) return; try { const saved = await api<Product>(`admin/products/${p.id}`, { method: 'DELETE' }); setProducts(x => x.map(i => i.id === saved.id ? saved : i)); } catch (e) { setError(e instanceof Error ? e.message : 'حذف ناموفق بود.'); } }

  async function openGuide(p: Product) { setEditing(p); setGuideOpen(true); setGuide(null); try { const g = await api<Guide>(`admin/products/${p.id}/guide`); setGuide(g); setGuideTitle(g?.title ?? ''); setGuideDescription(g?.description ?? ''); setSteps(g?.steps ?? []); } catch (e) { setError(e instanceof Error ? e.message : 'خطا در دریافت راهنما'); } }
  function addStep() { setSteps(s => [...s, blankStep()]); }
  function updateStep(index: number, patch: Partial<Step>) { setSteps(s => s.map((x, i) => i === index ? { ...x, ...patch } : x)); }
  function removeStep(index: number) { setSteps(s => s.filter((_, i) => i !== index)); }
  async function saveGuide() { if (!editing) return; if (!guideTitle.trim()) return setError('عنوان راهنما الزامی است.'); setSaving(true); try { await api(`admin/products/${editing.id}/guide`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: guideTitle, description: guideDescription || null, active: true, steps }) }); setGuideOpen(false); } catch (e) { setError(e instanceof Error ? e.message : 'ذخیره راهنما ناموفق بود.'); } finally { setSaving(false); } }
  async function deleteGuide() { if (!editing || !confirm('راهنمای این محصول غیرفعال شود؟')) return; await api(`admin/products/${editing.id}/guide`, { method: 'DELETE' }); setGuideOpen(false); }

  return <div className="space-y-6">
    <header className="flex items-center justify-between gap-4"><div><Link href="/admin/services" className="mb-3 inline-flex items-center gap-2 text-xs text-white/40 hover:text-cyan-300"><ArrowRight size={15}/> بازگشت به سرویس‌ها</Link><h1 className="text-3xl font-black">{serviceTitle}</h1><p className="mt-2 text-sm text-white/40">مدیریت محصولات و Guide مرحله‌به‌مرحله هر محصول</p></div><button onClick={createProduct} className="flex items-center gap-2 rounded-2xl bg-cyan-400 px-5 py-3 font-bold text-slate-950"><Plus size={18}/> محصول جدید</button></header>
    {error && <div className="rounded-2xl bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}
    {loading ? <div className="p-20 text-center text-white/40">در حال بارگذاری...</div> : <div className="grid gap-4 xl:grid-cols-2">{products.map(p => <article key={p.id} className="rounded-3xl border border-white/10 bg-white/[0.035] p-5"><div className="flex justify-between"><div className="flex gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-cyan-400/10 text-cyan-300">{p.icon || '◈'}</div><div><h2 className="font-bold">{p.title}</h2><div className="mt-1 text-xs text-white/35">{p.price} {p.currency}</div></div></div><span className={`rounded-full px-3 py-1 text-[11px] ${p.active ? 'bg-emerald-400/10 text-emerald-300' : 'bg-white/10 text-white/40'}`}>{p.active ? 'فعال' : 'غیرفعال'}</span></div><p className="mt-4 text-sm leading-6 text-white/45">{p.description}</p><div className="mt-4 flex gap-2"><span className="rounded-xl bg-white/5 px-3 py-2 text-xs text-white/45">{p.requiresGuide ? 'Guide فعال' : 'بدون Guide'}</span></div><div className="mt-5 grid grid-cols-[1fr_auto_auto_auto] gap-2 border-t border-white/5 pt-4"><button onClick={() => void openGuide(p)} className="rounded-2xl bg-cyan-400/10 py-3 text-xs font-bold text-cyan-300">مدیریت Guide</button><button onClick={() => editProduct(p)} className="rounded-2xl border border-white/10 px-3"><Edit3 size={16}/></button><button onClick={() => void toggle(p)} className="rounded-2xl border border-white/10 px-3"><Power size={16}/></button><button onClick={() => void remove(p)} className="rounded-2xl border border-red-400/10 px-3 text-red-300"><Trash2 size={16}/></button></div></article>)}</div>}

    {productOpen && <Modal title={editing ? 'ویرایش محصول' : 'محصول جدید'} close={() => setProductOpen(false)}><div className="grid gap-4 md:grid-cols-2"><label>عنوان<input className={`${input} mt-2`} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>قیمت<input className={`${input} mt-2`} value={form.price} onChange={e=>setForm({...form,price:e.target.value})} dir="ltr"/></label><label className="md:col-span-2">توضیحات<textarea className={`${input} mt-2 min-h-28`} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>واحد پول<input className={`${input} mt-2`} value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}/></label><label>Icon<input className={`${input} mt-2`} value={form.icon} onChange={e=>setForm({...form,icon:e.target.value})}/></label><label className="flex items-center gap-2 rounded-2xl border border-white/10 p-4"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> فعال</label><label className="flex items-center gap-2 rounded-2xl border border-white/10 p-4"><input type="checkbox" checked={form.requiresGuide} onChange={e=>setForm({...form,requiresGuide:e.target.checked})}/> دارای Guide</label></div><button disabled={saving} onClick={()=>void saveProduct()} className="mt-6 flex w-full items-center justify-center gap-2 rounded-2xl bg-cyan-400 py-3 font-black text-slate-950"><Save size={17}/>{saving?'در حال ذخیره...':'ذخیره محصول'}</button></Modal>}

    {guideOpen && <Modal title={`Guide — ${editing?.title ?? ''}`} close={() => setGuideOpen(false)} wide><div className="space-y-5"><div className="rounded-3xl border border-cyan-400/10 bg-cyan-400/[0.03] p-4"><div className="text-xs text-cyan-300">Guide فقط در Product</div><p className="mt-1 text-xs text-white/35">هر مرحله یک توضیح و در صورت نیاز یک Media (تصویر یا ویدیو) دارد.</p></div><label>عنوان راهنما<input className={`${input} mt-2`} value={guideTitle} onChange={e=>setGuideTitle(e.target.value)}/></label><label>توضیحات راهنما<textarea className={`${input} mt-2 min-h-24`} value={guideDescription} onChange={e=>setGuideDescription(e.target.value)}/></label><div className="flex items-center justify-between"><h3 className="font-bold">مراحل ({steps.length})</h3><button onClick={addStep} className="flex items-center gap-2 rounded-xl bg-cyan-400/10 px-3 py-2 text-xs text-cyan-300"><Plus size={15}/> مرحله جدید</button></div>{steps.map((s,i)=><StepEditor key={i} step={s} index={i} update={updateStep} remove={removeStep}/>)}{guide && <button onClick={()=>void deleteGuide()} className="text-xs text-red-300">غیرفعال کردن Guide</button>}<button disabled={saving} onClick={()=>void saveGuide()} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-cyan-400 py-3 font-black text-slate-950"><Save size={17}/>{saving?'در حال ذخیره...':'ذخیره Guide'}</button></div></Modal>}
  </div>;
}

function StepEditor({ step, index, update, remove }: { step: Step; index: number; update: (i:number,p:Partial<Step>)=>void; remove:(i:number)=>void }) {
  const [open,setOpen]=useState(true);
  return <div className="rounded-3xl border border-white/10 bg-white/[0.025] p-4"><div className="flex items-center justify-between"><button onClick={()=>setOpen(!open)} className="flex items-center gap-3 text-sm font-bold"><span className="grid h-8 w-8 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300">{index+1}</span>{step.title || 'مرحله بدون عنوان'}{open?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button><button onClick={()=>remove(index)} className="text-red-300"><Trash2 size={16}/></button></div>{open&&<div className="mt-4 space-y-3"><input className={input} value={step.title} onChange={e=>update(index,{title:e.target.value})} placeholder="عنوان مرحله"/><textarea className={`${input} min-h-32`} value={step.content} onChange={e=>update(index,{content:e.target.value})} placeholder="توضیح کامل مرحله"/><div className="grid gap-3 md:grid-cols-2"><select className={input} value={step.mediaType ?? ''} onChange={e=>update(index,{mediaType:(e.target.value||null) as Step['mediaType']})}><option value="">بدون Media</option><option value="image">تصویر</option><option value="video">ویدیو</option></select><input className={input} value={step.mediaUrl ?? ''} onChange={e=>update(index,{mediaUrl:e.target.value||null})} placeholder="URL تصویر یا ویدیو" dir="ltr"/></div><label className="flex items-center gap-2 text-xs text-white/55"><input type="checkbox" checked={step.requiresInput} onChange={e=>update(index,{requiresInput:e.target.checked})}/> این مرحله ورودی کاربر دارد</label>{step.requiresInput&&<div className="grid gap-3 md:grid-cols-2"><input className={input} value={step.inputKey ?? ''} onChange={e=>update(index,{inputKey:e.target.value})} placeholder="inputKey" dir="ltr"/><input className={input} value={step.inputLabel ?? ''} onChange={e=>update(index,{inputLabel:e.target.value})} placeholder="عنوان ورودی"/></div>}</div>}</div>;
}
function Modal({ title, close, children, wide=false }: { title:string; close:()=>void; children:React.ReactNode; wide?:boolean }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><div className={`${wide?'max-w-4xl':'max-w-2xl'} max-h-[92vh] w-full overflow-y-auto rounded-[2rem] border border-white/10 bg-[#0b1220] p-6`}><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-black">{title}</h2><button onClick={close}><X/></button></div>{children}</div></div>; }
