'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, ChevronLeft, ChevronRight, Clock3, Copy, CreditCard, Loader2, Phone, ReceiptText, RefreshCw, ShieldCheck, UserRound, XCircle } from 'lucide-react';
import { useParams, useRouter } from 'next/navigation';
import { api, fa } from '../../../../lib/api';

type OtpCode = { code: string | null; message: string | null; revision: number; receivedAt: string };
type Transaction = { id: string; type: string; amount: string; currency: string; balanceBefore: string; balanceAfter: string; description: string | null; createdAt: string; referenceType?: string | null; referenceId?: string | null };
type Item = { id: string; kind: 'ORDER' | 'SMSCODE'; status: string; amount: string; currency: string; createdAt: string; updatedAt: string; product?: { id: string; title: string } | null; service?: { id: string; title: string } | null; phoneNumber?: string | null; refunded?: boolean; providerOrderId?: string | null };
type User = { id: string; telegramId: string; username: string | null; firstName: string | null; lastName: string | null; photoUrl: string | null };
type ListResponse = { found: boolean; user: User; items: Item[]; page: number; limit: number; total: number; pages: number; statuses: string[] };
type Detail = { found: boolean; kind?: 'ORDER' | 'SMSCODE' | 'NUMBER_ORDER'; user?: User; order?: Record<string, unknown>; numberOrder?: Record<string, unknown>; product?: Record<string, unknown> | null; service?: Record<string, unknown> | null; sms?: Record<string, unknown>; otpCodes?: OtpCode[]; transactions?: Transaction[] };
const date = (v: unknown) => v ? new Date(String(v)).toLocaleString('fa-IR', { dateStyle: 'medium', timeStyle: 'short' }) : '—';
const money = (v: unknown, c = 'IRT') => `${fa(Number(v || 0))} ${c}`;
const active = ['CREATING', 'PROVIDER_PENDING', 'ACTIVE', 'OTP_RECEIVED'];
const statusLabel = (s: string) => ({ IN_PROCESS: 'در حال پردازش', VERIFY: 'در انتظار تأیید', SUCCESS: 'موفق', EXPIRED: 'منقضی شده', CANCEL: 'لغو شده', CREATING: 'در حال ایجاد', PROVIDER_PENDING: 'در انتظار سرویس‌دهنده', ACTIVE: 'فعال', OTP_RECEIVED: 'کد دریافت شد', COMPLETED: 'تکمیل شده', CANCELLED: 'لغو شده', FAILED: 'ناموفق', REFUNDED: 'بازگشت وجه' } as Record<string, string>)[s] ?? s;

export default function UserOrdersPage() {
  const params = useParams<{ userid: string }>(); const userId = params.userid; const router = useRouter();
  const [data, setData] = useState<ListResponse | null>(null); const [page, setPage] = useState(1); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<Detail | null>(null); const [detailLoading, setDetailLoading] = useState(false); const [actionLoading, setActionLoading] = useState(''); const [error, setError] = useState('');
  const load = async (p = page, s = status) => { setLoading(true); setError(''); try { setData(await api<ListResponse>(`admin/users/${encodeURIComponent(userId)}/orders?page=${p}&limit=10&status=${encodeURIComponent(s)}`)); } catch (e) { setError(e instanceof Error ? e.message : 'خطا در دریافت سفارش‌ها'); } finally { setLoading(false); } };
  useEffect(() => { if (userId) void load(1, status); }, [userId, status]);
  const open = async (item: Item) => { setDetailLoading(true); try { setSelected(await api<Detail>(`admin/users/${encodeURIComponent(userId)}/orders/${encodeURIComponent(item.id)}?kind=${item.kind}`)); } finally { setDetailLoading(false); } };
  const action = async (name: 'resend' | 'cancel' | 'sync') => { if (!selected?.order?.id || selected.kind === 'NUMBER_ORDER') return; setActionLoading(name); try { await api(`admin/users/${userId}/orders/${selected.order.id}/sms/${name}`, { method: 'POST' }); const refreshed = await api<Detail>(`admin/users/${userId}/orders/${selected.order.id}?kind=SMSCODE`); setSelected(refreshed); void load(page, status); } catch (e) { setError(e instanceof Error ? e.message : 'عملیات ناموفق بود'); } finally { setActionLoading(''); } };
  const statuses = useMemo(() => data?.statuses ?? [], [data]);
  if (loading && !data) return <div className="grid min-h-[500px] place-items-center"><Loader2 className="animate-spin text-cyan-300" /></div>;
  if (error && !data) return <div dir="rtl" className="rounded-[26px] border border-rose-400/10 bg-[#0b111a] p-10 text-center text-rose-300">{error}</div>;
  if (!data?.found) return <div dir="rtl" className="p-10 text-center text-white/30">کاربر پیدا نشد.</div>;
  const user = data.user;
  return <div dir="rtl" className="space-y-5 text-white">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><button onClick={() => router.push('/admin/user')} className="rounded-xl border border-white/10 p-2 text-white/50 hover:bg-white/5"><ArrowRight size={17} /></button><div className="grid h-12 w-12 place-items-center overflow-hidden rounded-2xl bg-cyan-400/10 text-cyan-300">{user.photoUrl ? <img src={user.photoUrl} alt="" className="h-full w-full object-cover" /> : <UserRound size={20} />}</div><div><div className="font-black text-xl">{user.firstName || user.lastName ? `${user.firstName ?? ''} ${user.lastName ?? ''}`.trim() : 'کاربر'}</div><div className="mt-1 text-xs text-white/35">Telegram ID: {user.telegramId}{user.username ? ` · @${user.username}` : ''}</div></div></div><div className="rounded-2xl border border-white/10 bg-[#0b111a] px-4 py-3 text-xs text-white/45">{fa(data.total)} سفارش</div></div>
    <div className="flex flex-wrap gap-2">{['', ...statuses].map((s) => <button key={s || 'ALL'} onClick={() => { setStatus(s); setPage(1); }} className={`rounded-xl border px-3 py-2 text-xs font-bold ${status === s ? 'border-cyan-300/40 bg-cyan-300/10 text-cyan-200' : 'border-white/10 text-white/35 hover:bg-white/5'}`}>{s || 'همه وضعیت‌ها'}</button>)}</div>
    <div className="overflow-hidden rounded-[26px] border border-white/10 bg-[#0b111a]"><div className="divide-y divide-white/[0.05]">{loading ? <div className="grid min-h-[300px] place-items-center"><Loader2 className="animate-spin text-cyan-300" /></div> : data.items.length ? data.items.map((item) => <button key={`${item.kind}-${item.id}`} onClick={() => void open(item)} className="grid w-full gap-3 px-5 py-4 text-right transition hover:bg-white/[0.025] md:grid-cols-[1.3fr_.8fr_.8fr_1fr] md:items-center"><div><div className="font-bold">{item.service?.title || item.product?.title || (item.kind === 'SMSCODE' ? 'SMSCode' : 'سفارش سرویس')}</div><div className="mt-1 text-[11px] text-white/25">{item.kind} · {item.id}</div></div><div className="text-sm text-white/55">{money(item.amount, item.currency)}</div><div><span className="rounded-lg border border-white/10 bg-white/[0.03] px-2 py-1 text-[10px] text-white/55">{statusLabel(item.status)}</span>{item.phoneNumber ? <div className="mt-2 flex items-center gap-1 text-xs text-cyan-300"><Phone size={12} />{item.phoneNumber}</div> : null}</div><div className="text-xs text-white/30">{date(item.createdAt)}</div></button>) : <div className="grid min-h-[300px] place-items-center text-sm text-white/30">سفارشی با این وضعیت پیدا نشد.</div>}</div>{data.pages > 1 && <div className="flex items-center justify-between border-t border-white/[0.06] px-5 py-4"><button disabled={data.page <= 1} onClick={() => { setPage(data.page - 1); void load(data.page - 1, status); }} className="rounded-xl border border-white/10 p-2 disabled:opacity-20"><ChevronRight size={17} /></button><span className="text-xs text-white/35">صفحه {fa(data.page)} از {fa(data.pages)}</span><button disabled={data.page >= data.pages} onClick={() => { setPage(data.page + 1); void load(data.page + 1, status); }} className="rounded-xl border border-white/10 p-2 disabled:opacity-20"><ChevronLeft size={17} /></button></div>}</div>
    {selected && <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-0 backdrop-blur-sm md:items-center md:p-6"><div className="max-h-[92vh] w-full max-w-5xl overflow-auto rounded-t-[28px] border border-white/10 bg-[#090f17] p-5 md:rounded-[28px]"><div className="mb-5 flex items-center justify-between"><div><div className="text-xs text-white/30">جزئیات سفارش</div><h2 className="mt-1 text-xl font-black">{selected.kind === 'NUMBER_ORDER' ? String(selected.product?.title ?? 'سفارش شماره') : selected.service?.title ? String(selected.service.title) : selected.kind === 'SMSCODE' ? 'SMSCode Order' : 'Service Order'}</h2></div><button onClick={() => setSelected(null)} className="rounded-xl border border-white/10 p-2 text-white/45"><XCircle size={18} /></button></div>{detailLoading ? <div className="grid min-h-[300px] place-items-center"><Loader2 className="animate-spin text-cyan-300" /></div> : <OrderDetail detail={selected} action={action} actionLoading={actionLoading} />}</div></div>}
  </div>;
}

function OrderDetail({ detail, action, actionLoading }: { detail: Detail; action: (name: 'resend' | 'cancel' | 'sync') => void; actionLoading: string }) {
  const order = detail.order ?? {}; const sms = detail.sms ?? {}; const isSms = detail.kind === 'SMSCODE'; const isNumber = detail.kind === 'NUMBER_ORDER'; const isActive = isSms && active.includes(String(order.status)); const canCancel = Boolean(sms.canCancel ?? order.canCancel) && isActive; const canResend = Boolean(sms.canResend ?? order.canResend) && isActive;
  const otpCodes = detail.otpCodes ?? (Array.isArray(order.otpCodes) ? order.otpCodes as OtpCode[] : []);
  const transactions = detail.transactions ?? (Array.isArray(order.transactions) ? order.transactions as Transaction[] : []);

  if (isNumber) {
    const metadata = order.metadata && typeof order.metadata === 'object' ? order.metadata as Record<string, unknown> : {};
    return <div className="space-y-4">
      <div className="grid gap-3 sm:grid-cols-4"><Box title="Status" value={statusLabel(String(order.status ?? '—'))} /><Box title="مبلغ" value={money(order.amount, String(order.currency ?? 'IRT'))} /><Box title="ثبت" value={date(order.createdAt)} /><Box title="Order Number" value={String(order.orderNumber ?? '—')} copy /></div>
      <section className="rounded-2xl border border-cyan-300/10 bg-cyan-300/[0.03] p-4"><h3 className="mb-4 flex items-center gap-2 font-black text-cyan-200"><Phone size={17} /> اطلاعات شماره</h3><div className="grid gap-3 sm:grid-cols-2"><Box title="Number Order ID" value={String(order.id ?? '—')} copy /><Box title="SMSCode Order ID" value={String(order.smsCodeOrderId ?? '—')} copy /><Box title="شماره" value={String(order.phoneNumber ?? '—')} copy /><Box title="Provider Order ID" value={String(metadata.providerOrderId ?? '—')} copy /><Box title="انقضا" value={date(metadata.expiresAt)} /><Box title="Service" value={String(detail.service?.title ?? '—')} /><Box title="Product" value={String(detail.product?.title ?? '—')} /><Box title="Product ID" value={String(detail.product?.id ?? '—')} copy /></div></section>
      <section className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><h3 className="mb-4 flex items-center gap-2 font-black"><ReceiptText size={16} /> کدهای دریافت‌شده ({fa(otpCodes.length)})</h3>{otpCodes.length ? <div className="space-y-2">{otpCodes.map((otp, i) => <div key={`${otp.revision}-${i}`} className="rounded-xl border border-white/8 bg-white/[0.02] p-3"><div className="flex items-center justify-between gap-3"><span className="font-mono text-lg font-black tracking-widest text-cyan-200">{otp.code || 'کد شناسایی نشد'}</span><span className="text-[9px] text-white/25">پیامک {otp.revision || i + 1} · {date(otp.receivedAt)}</span></div>{otp.message ? <p className="mt-2 text-xs leading-5 text-white/40">{otp.message}</p> : null}</div>)}</div> : <p className="text-xs text-white/30">کدی برای این سفارش ثبت نشده است.</p>}</section>
      <section className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><h3 className="mb-4 flex items-center gap-2 font-black"><CreditCard size={16} /> تراکنش‌های مرتبط ({fa(transactions.length)})</h3>{transactions.length ? <div className="space-y-2">{transactions.map((tx) => <div key={tx.id} className="rounded-xl border border-white/8 bg-white/[0.02] p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-white/65">{tx.description || tx.type}</p><p className="mt-1 text-[9px] text-white/25">{tx.type} · {date(tx.createdAt)}</p></div><span className={Number(tx.amount) < 0 ? 'font-black text-rose-200' : 'font-black text-emerald-200'}>{money(tx.amount, tx.currency)}</span></div><div className="mt-2 grid gap-2 text-[9px] text-white/30 sm:grid-cols-2"><span>موجودی قبل: {money(tx.balanceBefore, tx.currency)}</span><span>موجودی بعد: {money(tx.balanceAfter, tx.currency)}</span><span>Reference Type: {tx.referenceType ?? '—'}</span><span>Reference ID: {tx.referenceId ?? '—'}</span><span>Transaction ID: {tx.id}</span></div></div>)}</div> : <p className="text-xs text-white/30">تراکنشی برای این سفارش ثبت نشده است.</p>}</section>
      <section className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><h3 className="mb-4 font-black">کاربر</h3><div className="grid gap-3 sm:grid-cols-2"><Box title="User ID" value={String(detail.user?.id ?? '—')} copy /><Box title="Telegram ID" value={String(detail.user?.telegramId ?? '—')} copy /><Box title="Username" value={detail.user?.username ? `@${detail.user.username}` : '—'} /></div></section>
    </div>;
  }

  return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Box title="Status" value={statusLabel(String(order.status ?? '—'))} /><Box title="مبلغ" value={money(order.amount ?? order.chargedAmount, String(order.currency ?? 'IRT'))} /><Box title="ثبت" value={date(order.createdAt)} /></div><div className="grid gap-4 md:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><h3 className="mb-4 font-black">مشخصات سفارش</h3><div className="grid gap-3 sm:grid-cols-2"><Box title="Order ID" value={String(order.id)} copy /><Box title="Product" value={String(detail.product?.title ?? '—')} /><Box title="Service" value={String(detail.service?.title ?? '—')} /><Box title="Provider Order" value={String(order.providerOrderId ?? '—')} copy /></div></section>{isSms ? <section className="rounded-2xl border border-cyan-300/10 bg-cyan-300/[0.03] p-4"><div className="mb-4 flex items-center gap-2 font-black text-cyan-200"><ShieldCheck size={17} /> کنترل شماره</div><div className="grid gap-3 sm:grid-cols-2"><Box title="شماره" value={String(sms.phoneNumber ?? order.phoneNumber ?? '—')} copy /><Box title="وضعیت شماره" value={String(sms.status ?? order.status ?? '—')} /><Box title="انقضا" value={date(sms.expiresAt ?? order.expiresAt)} /><Box title="SMS Revision" value={String(sms.smsRevision ?? order.smsRevision ?? 0)} /></div>{isActive && <div className="mt-4 flex flex-wrap gap-2"><button disabled={Boolean(actionLoading) || !canResend} onClick={() => action('resend')} className="inline-flex items-center gap-2 rounded-xl border border-cyan-300/20 bg-cyan-300/10 px-3 py-2 text-xs font-bold text-cyan-200 disabled:opacity-30"><RefreshCw size={14} />{actionLoading === 'resend' ? 'در حال ارسال...' : 'دریافت مجدد SMS'}</button><button disabled={Boolean(actionLoading) || !canCancel} onClick={() => action('cancel')} className="inline-flex items-center gap-2 rounded-xl border border-rose-300/20 bg-rose-300/10 px-3 py-2 text-xs font-bold text-rose-200 disabled:opacity-30"><XCircle size={14} />{actionLoading === 'cancel' ? 'در حال لغو...' : 'لغو شماره'}</button><button disabled={Boolean(actionLoading)} onClick={() => action('sync')} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs text-white/55 disabled:opacity-30"><Clock3 size={14} />همگام‌سازی وضعیت</button></div>}</section> : <section className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><h3 className="mb-4 font-black">کاربر</h3><div className="text-sm text-white/60">{detail.user?.firstName} {detail.user?.lastName}</div><div className="mt-2 text-xs text-white/30">Telegram ID: {detail.user?.telegramId}</div></section>}</div></div>;
}
function Box({ title, value, copy = false }: { title: string; value: string; copy?: boolean }) { return <div className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-3"><div className="mb-1 text-[10px] text-white/25">{title}</div><div className="flex items-center gap-2 break-all text-sm text-white/65"><span className="min-w-0 flex-1">{value}</span>{copy && value !== '—' ? <button onClick={() => void navigator.clipboard?.writeText(value)} className="text-white/25 hover:text-cyan-300"><Copy size={13} /></button> : null}</div></div>; }
