'use client';

import { useEffect, useState } from 'react';
import { ArrowRight, ChevronLeft, ChevronRight, Loader2, Search } from 'lucide-react';
import { useParams, useRouter } from 'next/navigation';
import { api, fa } from '../../../../../lib/api';

type Transaction = { id: string; type: string; amount: string; balanceBefore: string; balanceAfter: string; currency: string; referenceType: string | null; referenceId: string | null; description: string | null; createdAt: string };
type Response = { found: boolean; user?: { id: string; telegramId: string; username: string | null; firstName: string | null; lastName: string | null; photoUrl: string | null }; items: Transaction[]; page: number; limit: number; total: number; pages: number };
const labels: Record<string, string> = { DEPOSIT: 'واریز', PAYMENT_DEPOSIT: 'واریز', PURCHASE: 'خرید سرویس', SMSCODE_ORDER: 'خرید شماره', SMSCODE_ORDER_DEBIT: 'خرید شماره', SMSCODE_ORDER_REFUND: 'بازگشت وجه', REFUND: 'بازگشت وجه', WITHDRAW: 'برداشت', WITHDRAWAL: 'برداشت' };
const money = (v: string, c: string) => `${fa(Number(v || 0))} ${c}`;
const date = (v: string) => new Date(v).toLocaleString('fa-IR', { dateStyle: 'medium', timeStyle: 'short' });

export default function UserTransactionsPage() {
  const { userId } = useParams<{ userId: string }>(); const router = useRouter();
  const [data, setData] = useState<Response | null>(null); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true);
  useEffect(() => { const timer = window.setTimeout(() => { setLoading(true); void api<Response>(`admin/users/${userId}/transactions?page=${page}&limit=20&search=${encodeURIComponent(search)}`).then(setData).finally(() => setLoading(false)); }, 250); return () => window.clearTimeout(timer); }, [userId, page, search]);
  const name = [data?.user?.firstName, data?.user?.lastName].filter(Boolean).join(' ') || (data?.user?.username ? `@${data.user.username}` : 'کاربر');
  return <div dir="rtl" className="space-y-5 text-white"><div className="flex flex-wrap items-center justify-between gap-4"><div><button onClick={() => router.back()} className="mb-3 inline-flex items-center gap-2 text-xs text-white/40 hover:text-white"><ArrowRight size={15}/> بازگشت</button><h1 className="text-2xl font-black">تراکنش‌های {name}</h1><p className="mt-1 text-xs text-white/35">Telegram ID: {data?.user?.telegramId || '—'} · {fa(data?.total ?? 0)} تراکنش</p></div><div className="relative w-full max-w-md"><Search size={16} className="absolute right-3 top-1/2 -translate-y-1/2 text-white/25"/><input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="جستجوی شناسه، نوع، reference یا شرح..." className="h-11 w-full rounded-xl border border-white/10 bg-[#0b111a] pr-10 pl-3 text-sm outline-none focus:border-cyan-400/30"/></div></div>
  <section className="overflow-hidden rounded-[26px] border border-white/10 bg-[#0b111a]"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-right text-sm"><thead className="bg-white/[.025] text-[11px] text-white/35"><tr><th className="px-4 py-3">شناسه</th><th className="px-4 py-3">نوع</th><th className="px-4 py-3">مبلغ</th><th className="px-4 py-3">قبل</th><th className="px-4 py-3">بعد</th><th className="px-4 py-3">Reference</th><th className="px-4 py-3">شرح</th><th className="px-4 py-3">زمان</th></tr></thead><tbody className="divide-y divide-white/[.06]">{loading ? <tr><td colSpan={8} className="h-52 text-center"><Loader2 className="mx-auto animate-spin text-cyan-300"/></td></tr> : data?.items.map(t => <tr key={t.id} className="hover:bg-white/[.025]"><td className="px-4 py-3 text-xs text-white/45" title={t.id}>{t.id.slice(0, 8)}…</td><td className="px-4 py-3"><span className="rounded-lg bg-cyan-400/10 px-2.5 py-1 text-[10px] font-bold text-cyan-300">{labels[t.type] ?? t.type}</span></td><td className={`px-4 py-3 font-bold ${Number(t.amount) >= 0 ? 'text-emerald-300' : 'text-rose-300'}`}>{Number(t.amount) >= 0 ? '+' : ''}{money(t.amount, t.currency)}</td><td className="px-4 py-3 text-white/45">{money(t.balanceBefore, t.currency)}</td><td className="px-4 py-3 text-white/60">{money(t.balanceAfter, t.currency)}</td><td className="px-4 py-3 text-xs text-white/35">{t.referenceType || '—'}{t.referenceId ? ` / ${t.referenceId}` : ''}</td><td className="max-w-[220px] truncate px-4 py-3 text-white/40">{t.description || '—'}</td><td className="whitespace-nowrap px-4 py-3 text-xs text-white/35">{date(t.createdAt)}</td></tr>)}{!loading && !data?.items.length ? <tr><td colSpan={8} className="h-52 text-center text-white/30">تراکنشی برای این کاربر پیدا نشد.</td></tr> : null}</tbody></table></div><div className="flex items-center justify-between border-t border-white/[.06] px-5 py-4"><span className="text-xs text-white/30">{fa(data?.total ?? 0)} تراکنش</span><div className="flex items-center gap-2"><button disabled={page <= 1 || loading} onClick={() => setPage(page - 1)} className="rounded-xl border border-white/10 p-2 disabled:opacity-20"><ChevronRight size={16}/></button><span className="text-xs text-white/35">صفحه {fa(page)} از {fa(Math.max(1, data?.pages ?? 1))}</span><button disabled={page >= (data?.pages ?? 1) || loading} onClick={() => setPage(page + 1)} className="rounded-xl border border-white/10 p-2 disabled:opacity-20"><ChevronLeft size={16}/></button></div></div></section></div>;
}
