'use client';

import { useEffect, useMemo, useState } from 'react';

type User={id:string;telegramId:string;username:string|null;firstName:string|null;lastName:string|null;photoUrl:string|null};
type Wallet={id:string;balance:string;currency:string}; type Me={user:User;wallet:Wallet|null};
type Service={id:string;slug:string;title:string;description:string;icon:string};
type Product={id:string;serviceId:string;title:string;description:string;price:string;currency:string;icon:string};
type Step={id:string;position:number;title:string;content:string;imageUrl:string|null;requiresInput:boolean;inputKey:string|null;inputLabel:string|null};
type Guide={id:string;title:string;description:string|null;steps:Step[]};
type Progress={currentStep:number;completed:boolean}; type Order={id:string;status:string;amount:string;currency:string};
type GuideData={order:Order;product:Product;guide:Guide;steps:Step[];progress:Progress;inputs:{key:string;value:string}[]};
type Method={id:string;title:string;cardNumber:string;holderName:string;bankName:string|null};

const api=async<T,>(path:string,options?:RequestInit)=>{const r=await fetch(`/api/${path}`,{credentials:'include',...options});if(!r.ok){let text=await r.text();try{const j=JSON.parse(text);throw new Error(j.message||'Request failed')}catch(e){if(e instanceof Error&&e.message!=='Request failed')throw e;throw new Error(text||'Request failed')}}return r.json() as Promise<T>};
function initials(u:User){return `${u.firstName??''} ${u.lastName??''}`.trim().split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'U'}

export default function PanelPage(){
 const [me,setMe]=useState<Me|null>(null),[services,setServices]=useState<Service[]>([]),[products,setProducts]=useState<Product[]>([]),[methods,setMethods]=useState<Method[]>([]);
 const [loading,setLoading]=useState(true),[menu,setMenu]=useState(false),[deposit,setDeposit]=useState(false),[amount,setAmount]=useState(''),[method,setMethod]=useState(''),[receipt,setReceipt]=useState<File|null>(null),[message,setMessage]=useState('');
 const [guide,setGuide]=useState<GuideData|null>(null),[step,setStep]=useState(0),[input,setInput]=useState(''),[buying,setBuying]=useState(false);
 useEffect(()=>{Promise.all([api<Me>('auth/me'),api<Service[]>('services'),api<Product[]>('products'),api<Method[]>('payment-methods')]).then(([m,s,p,pm])=>{setMe(m);setServices(s);setProducts(p);setMethods(pm);setMethod(pm[0]?.id??'')}).catch(e=>setMessage(e.message)).finally(()=>setLoading(false))},[]);
 const displayName=useMemo(()=>[me?.user.firstName,me?.user.lastName].filter(Boolean).join(' ')||'Telegram User',[me]);
 const balance=Number(me?.wallet?.balance??0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
 async function buy(p:Product){setBuying(true);try{const created=await api<{order:Order;progress:Progress;guide:Guide|null}>('orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({productId:p.id})});if(!created.guide){setMessage('This product has no activation guide yet.');return}const data=await api<GuideData>(`orders/${created.order.id}/guide`);setGuide(data);setStep(data.progress.currentStep);const saved=data.inputs.find(x=>x.key===data.steps[data.progress.currentStep]?.inputKey);setInput(saved?.value??'')}catch(e){setMessage(e instanceof Error&&e.message==='INSUFFICIENT_BALANCE'?'Insufficient balance. Please add funds first.':e instanceof Error?e.message:'Purchase failed')}finally{setBuying(false)}}
 async function saveProgress(next:number){if(!guide)return;const current=guide.steps[step];const values=current?.requiresInput&&current.inputKey?{[current.inputKey]:input}:undefined;await api(`orders/${guide.order.id}/progress`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({step:next,values})});setStep(next);}
 async function submitDeposit(e:React.FormEvent){e.preventDefault();if(!receipt||!amount||!method)return setMessage('Enter the amount and upload your receipt.');const fd=new FormData();fd.append('amount',amount);fd.append('paymentMethodId',method);fd.append('receipt',receipt);try{await api('payments/card-transfer',{method:'POST',body:fd});setDeposit(false);setAmount('');setReceipt(null);setMessage('Deposit submitted for admin review.')}catch(e){setMessage(e instanceof Error?e.message:'Deposit failed')}}
 async function logout(){await api('auth/logout',{method:'POST'});location.reload()}
 if(loading)return <main className="min-h-screen grid place-items-center bg-[#070b14] text-white"><div className="animate-pulse rounded-3xl border border-white/10 bg-white/5 px-6 py-4">Loading dashboard…</div></main>;
 if(!me)return <main className="min-h-screen grid place-items-center bg-[#070b14] p-6 text-center text-white"><div><h1 className="text-xl font-bold">Mini App unavailable</h1><p className="mt-2 text-white/50">{message}</p></div></main>;
 const {user,wallet}=me; const current=guide?.steps[step]; const progressPct=guide?Math.round(((step+1)/guide.steps.length)*100):0;
 return <main className="min-h-screen bg-[#070b14] text-white selection:bg-cyan-300 selection:text-black"><div className="pointer-events-none fixed -left-32 -top-32 h-80 w-80 rounded-full bg-cyan-500/15 blur-3xl"/><div className="pointer-events-none fixed -right-32 top-1/3 h-96 w-96 rounded-full bg-violet-500/10 blur-3xl"/>
  <div className="relative mx-auto max-w-xl px-4 pb-28 pt-4">
   <header className="sticky top-0 z-30 -mx-4 mb-5 flex items-center justify-between border-b border-white/5 bg-[#070b14]/80 px-4 py-3 backdrop-blur-xl"><div><p className="text-[10px] font-bold uppercase tracking-[.28em] text-cyan-300/70">Store</p><h1 className="text-lg font-bold">Dashboard</h1></div><button onClick={()=>setMenu(!menu)} className="h-11 w-11 overflow-hidden rounded-2xl border border-white/10 bg-white/10 active:scale-95">{user.photoUrl?<img src={user.photoUrl} className="h-full w-full object-cover" alt=""/>:<span className="grid h-full w-full place-items-center font-bold">{initials(user)}</span>}</button>{menu&&<div className="absolute right-4 top-16 z-50 w-64 rounded-3xl border border-white/10 bg-[#111827]/95 p-2 shadow-2xl backdrop-blur-2xl"><div className="px-3 py-3"><p className="font-semibold">{displayName}</p><p className="text-xs text-white/45">{user.username?`@${user.username}`:user.telegramId}</p></div><button onClick={()=>setDeposit(true)} className="block w-full rounded-2xl px-3 py-3 text-left text-sm hover:bg-white/10">Wallet / Add funds</button><button onClick={()=>setMessage('Your purchased orders are available from the Orders section.')} className="block w-full rounded-2xl px-3 py-3 text-left text-sm hover:bg-white/10">My Accounts</button><button onClick={logout} className="mt-1 w-full rounded-2xl px-3 py-3 text-left text-sm text-red-300 hover:bg-red-500/10">Logout</button></div>}</header>
   <section className="mb-4 rounded-[30px] border border-white/10 bg-gradient-to-br from-cyan-400/20 via-white/[.07] to-violet-500/10 p-5 shadow-2xl"><div className="flex items-center gap-4"><div className="relative grid h-16 w-16 shrink-0 place-items-center overflow-hidden rounded-[22px] bg-gradient-to-br from-cyan-300 to-blue-600 text-xl font-black">{user.photoUrl?<img src={user.photoUrl} className="h-full w-full object-cover" alt=""/>:initials(user)}</div><div className="min-w-0"><p className="text-xs text-white/45">Welcome back</p><h2 className="truncate text-xl font-bold">{displayName}</h2><p className="truncate text-xs text-white/40">Ready to get started?</p></div></div></section>
   <section className="rounded-[30px] border border-white/10 bg-white/[.055] p-5 shadow-xl backdrop-blur-xl"><div className="flex items-start justify-between"><div><p className="text-xs text-white/45">Available balance</p><p className="mt-2 text-4xl font-black tracking-tight">{balance}</p></div><span className="rounded-xl border border-white/10 bg-white/10 px-3 py-2 text-[11px] font-bold text-white/60">{wallet?.currency??'USD'}</span></div><button onClick={()=>setDeposit(true)} className="mt-5 w-full rounded-2xl bg-white px-4 py-3 text-sm font-bold text-black transition hover:bg-cyan-100">+ Add funds</button></section>
   <div className="mt-7 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-cyan-300/60">Services</p><h2 className="mt-1 text-2xl font-black">Choose a service</h2></div><span className="text-xs text-white/35">{services.length} active</span></div>
   <section className="mt-4 space-y-3">{services.map(s=><div key={s.id}><div className="mb-2 flex items-center gap-2 text-xs text-white/40"><span>{s.icon==='apple'?'':'◈'}</span><span>{s.title}</span></div>{products.filter(p=>p.serviceId===s.id).map(p=><article key={p.id} className="group rounded-[28px] border border-white/10 bg-white/[.045] p-4 transition duration-300 hover:-translate-y-0.5 hover:border-cyan-300/20"><div className="flex items-center gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-white/10 text-2xl">{p.icon==='apple'?'':'◈'}</div><div className="min-w-0 flex-1"><h3 className="font-bold">{p.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-white/45">{p.description}</p></div><div className="text-right"><p className="text-sm font-black">{p.price} {p.currency}</p><button disabled={buying} onClick={()=>buy(p)} className="mt-2 rounded-xl bg-cyan-300 px-3 py-2 text-xs font-bold text-black disabled:opacity-50">{buying?'…':'Buy & Start'}</button></div></div></article>)}</div>)}</section>
   <section className="mt-7 grid grid-cols-2 gap-3">{[['✓','Guided setup'],['⚡','Fast support'],['🔒','Secure payments'],['◎','Clear pricing']].map(([i,t])=><div key={t} className="rounded-2xl border border-white/8 bg-white/[.035] p-4"><span className="text-lg">{i}</span><p className="mt-2 text-xs font-semibold text-white/65">{t}</p></div>)}</section>
   {message&&<button onClick={()=>setMessage('')} className="fixed bottom-5 left-1/2 z-[70] -translate-x-1/2 max-w-[90vw] rounded-2xl border border-white/10 bg-[#182235] px-4 py-3 text-xs text-white shadow-2xl">{message}</button>}
  </div>
  <nav className="fixed bottom-3 left-1/2 z-40 flex w-[calc(100%-24px)] max-w-md -translate-x-1/2 justify-around rounded-3xl border border-white/10 bg-[#111827]/90 p-2 shadow-2xl backdrop-blur-2xl"><span className="rounded-2xl bg-white/10 px-5 py-2.5 text-xs font-bold">Home</span><span className="px-5 py-2.5 text-xs text-white/40">Orders</span><span onClick={()=>setDeposit(true)} className="cursor-pointer px-5 py-2.5 text-xs text-white/40">Wallet</span><span onClick={()=>setMenu(true)} className="cursor-pointer px-5 py-2.5 text-xs text-white/40">Profile</span></nav>
  {guide&&current&&<div className="fixed inset-0 z-[60] overflow-y-auto bg-[#050812]/90 p-3 backdrop-blur-md"><div className="mx-auto flex min-h-full max-w-xl items-center py-6"><div className="w-full rounded-[32px] border border-white/10 bg-[#111827] p-5 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300/60">Activation</p><h2 className="mt-1 text-xl font-black">{guide.guide.title}</h2></div><button onClick={()=>setGuide(null)} className="rounded-xl bg-white/10 px-3 py-2">×</button></div><div className="mt-5"><div className="mb-2 flex justify-between text-[11px] text-white/40"><span>Step {step+1} of {guide.steps.length}</span><span>{progressPct}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-cyan-300 transition-all duration-500" style={{width:`${progressPct}%`}}/></div></div><div key={current.id} className="mt-7 animate-[fade_.25s_ease-out]"><div className="mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-cyan-300/10 text-2xl">{step+1}</div><h3 className="text-2xl font-black">{current.title}</h3><p className="mt-4 whitespace-pre-line text-sm leading-7 text-white/60">{current.content}</p>{current.requiresInput&&current.inputKey&&<div className="mt-5"><label className="mb-2 block text-xs font-semibold text-white/50">{current.inputLabel??current.inputKey}</label><input value={input} onChange={e=>setInput(e.target.value)} className="w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 outline-none focus:border-cyan-300/40" placeholder={current.inputLabel??''}/></div>}</div><div className="mt-8 flex gap-3"><button disabled={step===0} onClick={()=>saveProgress(step-1)} className="flex-1 rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-bold disabled:opacity-30">Previous</button>{step<guide.steps.length-1?<button onClick={()=>saveProgress(step+1)} className="flex-[1.5] rounded-2xl bg-cyan-300 px-4 py-3 text-sm font-black text-black">Next</button>:<button onClick={()=>{setGuide(null);setMessage('Setup completed successfully.')}} className="flex-[1.5] rounded-2xl bg-emerald-400 px-4 py-3 text-sm font-black text-black">Finish ✓</button>}</div></div></div></div>}
  {deposit&&<div className="fixed inset-0 z-50 grid place-items-end bg-black/60 p-3 backdrop-blur-sm sm:place-items-center"><form onSubmit={submitDeposit} className="w-full max-w-md rounded-[30px] border border-white/10 bg-[#111827] p-5 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs text-cyan-300/60">Wallet</p><h2 className="text-xl font-black">Add funds</h2></div><button type="button" onClick={()=>setDeposit(false)} className="rounded-xl bg-white/10 px-3 py-2">×</button></div><div className="mt-5 space-y-3"><input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="Amount" className="w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm outline-none"/><select value={method} onChange={e=>setMethod(e.target.value)} className="w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm outline-none">{methods.map(m=><option key={m.id} value={m.id}>{m.bankName??''} {m.cardNumber.slice(0,4)} **** {m.cardNumber.slice(-4)}</option>)}</select><label className="block rounded-2xl border border-dashed border-white/15 bg-white/[.03] p-4 text-sm text-white/55"><span className="font-semibold text-white">Upload receipt</span><input type="file" accept="image/*,application/pdf" onChange={e=>setReceipt(e.target.files?.[0]??null)} className="mt-3 block w-full text-xs"/></label><button className="w-full rounded-2xl bg-cyan-300 px-4 py-3 text-sm font-black text-black">Submit deposit</button></div></form></div>}
 </main>
}
