'use client';

import { useEffect, useMemo, useState } from 'react';

type User={id:string;telegramId:string;username:string|null;firstName:string|null;lastName:string|null;photoUrl:string|null};
type Wallet={id:string;balance:string;currency:string};
type Me={user:User;wallet:Wallet|null};
type Service={id:string;slug:string;title:string;description:string;icon:string};
type Product={id:string;serviceId:string;title:string;description:string;price:string;currency:string;icon:string};
type Step={id:string;position:number;title:string;content:string;imageUrl:string|null;requiresInput:boolean;inputKey:string|null;inputLabel:string|null};
type Guide={id:string;title:string;description:string|null;steps:Step[]};
type Progress={currentStep:number;completed:boolean};
type Order={id:string;status:string;amount:string;currency:string};
type GuideData={order:Order;product:Product;guide:Guide;steps:Step[];progress:Progress;inputs:{key:string;value:string}[]};
type Method={id:string;type:string;title:string;cardNumber:string;holderName:string;bankName:string|null};
type Notification={id:string;type:string;title:string;message:string;read:boolean;createdAt:string};

const api=async<T,>(path:string,options?:RequestInit)=>{const r=await fetch(`/api/${path}`,{credentials:'include',...options});if(!r.ok){const text=await r.text();try{const j=JSON.parse(text);throw new Error(j.message||'خطا در درخواست')}catch(e){if(e instanceof Error&&e.message!=='خطا در درخواست')throw e;throw new Error(text||'خطا در درخواست')}}return r.json() as Promise<T>};
const fa=(n:number|string)=>Number(n||0).toLocaleString('fa-IR');
function initials(u:User){return `${u.firstName??''} ${u.lastName??''}`.trim().split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'U'}

export default function PanelPage(){
 const [me,setMe]=useState<Me|null>(null),[services,setServices]=useState<Service[]>([]),[products,setProducts]=useState<Product[]>([]),[methods,setMethods]=useState<Method[]>([]),[notifications,setNotifications]=useState<Notification[]>([]);
 const [loading,setLoading]=useState(true),[menu,setMenu]=useState(false),[deposit,setDeposit]=useState(false),[depositStep,setDepositStep]=useState<'method'|'receipt'|'success'>('method');
 const [amount,setAmount]=useState(''),[method,setMethod]=useState(''),[receipt,setReceipt]=useState<File|null>(null),[submittingDeposit,setSubmittingDeposit]=useState(false),[message,setMessage]=useState(''),[realtime,setRealtime]=useState(false),[buying,setBuying]=useState(false);
 const [guide,setGuide]=useState<GuideData|null>(null),[step,setStep]=useState(0),[input,setInput]=useState(''),[savingStep,setSavingStep]=useState(false);

 useEffect(()=>{Promise.all([api<Me>('auth/me'),api<Service[]>('services'),api<Product[]>('products'),api<Method[]>('payment-methods'),api<Notification[]>('notifications')]).then(([m,s,p,pm,n])=>{setMe(m);setServices(s);setProducts(p);setMethods(pm);setNotifications(n);setMethod(pm.find(x=>x.type==='CARD_TRANSFER'&&x.id)?.id??'')}).catch(e=>setMessage(e instanceof Error?e.message:'خطا در بارگذاری')).finally(()=>setLoading(false))},[]);

 useEffect(()=>{if(!me)return;let source:EventSource|undefined;let retry:number|undefined;const connect=()=>{source=new EventSource('/api/notifications/stream');source.onopen=()=>setRealtime(true);source.onmessage=event=>{try{const e=JSON.parse(event.data);if(e.type==='connected')return;if(e.type==='notification'&&e.notification){setNotifications(prev=>[e.notification,...prev.filter(n=>n.id!==e.notification.id)].slice(0,50));setMessage(`${e.notification.title}: ${e.notification.message}`)}if(e.type==='wallet.updated'&&e.wallet){setMe(prev=>prev?{...prev,wallet:prev.wallet?{...prev.wallet,balance:String(e.wallet.balance),currency:e.wallet.currency}:null}:prev)}}catch{}};source.onerror=()=>{setRealtime(false);source?.close();retry=window.setTimeout(connect,4000)}};connect();return()=>{if(retry)clearTimeout(retry);source?.close();setRealtime(false)}},[me]);

 const displayName=useMemo(()=>[me?.user.firstName,me?.user.lastName].filter(Boolean).join(' ')||'کاربر تلگرام',[me]);
 const balance=fa(me?.wallet?.balance??0); const unread=notifications.filter(n=>!n.read).length;
 const cardMethods=methods.filter(x=>x.type==='CARD_TRANSFER');
 const selectedMethod=methods.find(x=>x.id===method&&x.type==='CARD_TRANSFER');
 const numericAmount=Number(amount.replace(/,/g,''));
 const canContinue=Boolean(selectedMethod)&&Number.isFinite(numericAmount)&&numericAmount>0;

 function openDeposit(){setDeposit(true);setDepositStep('method');setReceipt(null);setAmount('');if(!selectedMethod&&cardMethods[0])setMethod(cardMethods[0].id)}
 function closeDeposit(){if(submittingDeposit)return;setDeposit(false);setDepositStep('method');setReceipt(null);setAmount('')}
 function onAmount(v:string){setAmount(v.replace(/[^0-9.]/g,''))}

 async function submitDeposit(e:React.FormEvent){e.preventDefault();if(!selectedMethod||numericAmount<=0||!receipt)return setMessage('روش پرداخت، مبلغ و فیش واریزی را انتخاب کنید.');setSubmittingDeposit(true);try{const fd=new FormData();fd.append('amount',String(numericAmount));fd.append('paymentMethodId',selectedMethod.id);fd.append('receipt',receipt);await api('payments/card-transfer',{method:'POST',body:fd});setDepositStep('success');setReceipt(null)}catch(e){setMessage(e instanceof Error?e.message:'ثبت درخواست شارژ انجام نشد')}finally{setSubmittingDeposit(false)}}

 async function buy(p:Product){setBuying(true);try{const created=await api<{order:Order;progress:Progress;guide:Guide|null}>('orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({productId:p.id})});if(!created.guide){setMessage('برای این محصول هنوز راهنمای فعال‌سازی وجود ندارد.');return}const data=await api<GuideData>(`orders/${created.order.id}/guide`);setGuide(data);setStep(data.progress.currentStep);setInput(data.inputs.find(x=>x.key===data.steps[data.progress.currentStep]?.inputKey)?.value??'')}catch(e){setMessage(e instanceof Error&&e.message==='INSUFFICIENT_BALANCE'?'موجودی کافی نیست؛ ابتدا حساب را شارژ کنید.':e instanceof Error?e.message:'خرید انجام نشد')}finally{setBuying(false)}}
 async function saveProgress(next:number){if(!guide||savingStep)return;setSavingStep(true);try{const current=guide.steps[step];const values=current?.requiresInput&&current.inputKey?{[current.inputKey]:input}:undefined;await api(`orders/${guide.order.id}/progress`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({step:next,values})});setStep(next)}catch(e){setMessage(e instanceof Error?e.message:'ذخیره مرحله انجام نشد')}finally{setSavingStep(false)}}
 async function markRead(id:string){try{await api(`notifications/${id}/read`,{method:'POST'});setNotifications(prev=>prev.map(n=>n.id===id?{...n,read:true}:n))}catch(e){setMessage(e instanceof Error?e.message:'اعلان خوانده نشد')}}
 async function logout(){await api('auth/logout',{method:'POST'});location.reload()}

 if(loading)return <main dir="rtl" className="min-h-screen grid place-items-center bg-[#070b14] text-white"><div className="animate-pulse rounded-3xl border border-white/10 bg-white/5 px-6 py-4">در حال بارگذاری…</div></main>;
 if(!me)return <main dir="rtl" className="min-h-screen grid place-items-center bg-[#070b14] p-6 text-center text-white"><div><h1 className="text-xl font-bold">برنامه در دسترس نیست</h1><p className="mt-2 text-white/50">{message}</p></div></main>;
 const {user,wallet}=me;const current=guide?.steps[step];const progressPct=guide?Math.round(((step+1)/guide.steps.length)*100):0;

 return <main dir="rtl" className="min-h-screen bg-[#070b14] text-white selection:bg-cyan-300 selection:text-black"><div className="pointer-events-none fixed -left-32 -top-32 h-80 w-80 rounded-full bg-cyan-500/15 blur-3xl"/><div className="pointer-events-none fixed -right-32 top-1/3 h-96 w-96 rounded-full bg-violet-500/10 blur-3xl"/><div className="relative mx-auto max-w-xl px-4 pb-28 pt-4">
 <header className="sticky top-0 z-30 -mx-4 mb-5 flex items-center justify-between border-b border-white/5 bg-[#070b14]/80 px-4 py-3 backdrop-blur-xl"><div><p className="text-[10px] font-bold tracking-[.22em] text-cyan-300/70">فروشگاه</p><h1 className="text-lg font-bold">داشبورد</h1></div><div className="flex items-center gap-2"><span title={realtime?'اتصال لحظه‌ای فعال است':'در حال اتصال…'} className={`h-2.5 w-2.5 rounded-full ${realtime?'bg-emerald-400 shadow-[0_0_12px_rgba(52,211,153,.7)]':'bg-amber-400'}`}/><button onClick={()=>setMenu(v=>!v)} className="relative h-11 w-11 overflow-hidden rounded-2xl border border-white/10 bg-white/10 active:scale-95">{user.photoUrl?<img src={user.photoUrl} className="h-full w-full object-cover" alt="پروفایل"/>:<span className="grid h-full w-full place-items-center font-bold">{initials(user)}</span>}{unread>0&&<span className="absolute right-0 top-0 grid h-4 min-w-4 place-items-center rounded-full bg-red-400 px-1 text-[9px] font-black text-black">{unread>9?'۹+':fa(unread)}</span>}</button></div>{menu&&<div className="absolute left-4 top-16 z-50 w-72 rounded-3xl border border-white/10 bg-[#111827]/95 p-2 shadow-2xl backdrop-blur-2xl"><div className="px-3 py-3"><p className="font-semibold">{displayName}</p><p className="text-xs text-white/45">{user.username?`@${user.username}`:user.telegramId}</p></div><button onClick={openDeposit} className="block w-full rounded-2xl px-3 py-3 text-right text-sm hover:bg-white/10">کیف پول و شارژ حساب</button><p className="px-3 py-2 text-[10px] font-bold tracking-widest text-white/30">اعلان‌ها</p>{notifications.slice(0,5).map(n=><button key={n.id} onClick={()=>markRead(n.id)} className={`block w-full rounded-2xl px-3 py-3 text-right ${n.read?'opacity-50':'bg-white/5'}`}><p className="text-xs font-bold">{n.title}</p><p className="mt-1 line-clamp-2 text-[11px] text-white/45">{n.message}</p></button>)}{!notifications.length&&<p className="px-3 py-2 text-xs text-white/35">اعلانی وجود ندارد.</p>}<button onClick={logout} className="mt-1 w-full rounded-2xl px-3 py-3 text-right text-sm text-red-300 hover:bg-red-500/10">خروج از حساب</button></div>}</header>
 <section className="mb-4 rounded-[30px] border border-white/10 bg-gradient-to-br from-cyan-400/20 via-white/[.07] to-violet-500/10 p-5 shadow-2xl"><div className="flex items-center gap-4"><div className="grid h-16 w-16 shrink-0 place-items-center overflow-hidden rounded-[22px] bg-gradient-to-br from-cyan-300 to-blue-600 text-xl font-black">{user.photoUrl?<img src={user.photoUrl} className="h-full w-full object-cover" alt=""/>:initials(user)}</div><div className="min-w-0"><p className="text-xs text-white/45">خوش آمدید</p><h2 className="truncate text-xl font-bold">{displayName}</h2><p className="truncate text-xs text-white/40">موجودی و اعلان‌ها به‌صورت لحظه‌ای به‌روزرسانی می‌شوند.</p></div></div></section>
 <section className="rounded-[30px] border border-white/10 bg-white/[.055] p-5 shadow-xl backdrop-blur-xl"><div className="flex items-start justify-between"><div><p className="text-xs text-white/45">موجودی قابل استفاده</p><p className="mt-2 text-4xl font-black tracking-tight">{balance}</p></div><span className="rounded-xl border border-white/10 bg-white/10 px-3 py-2 text-[11px] font-bold text-white/60">{wallet?.currency??'USD'}</span></div><button onClick={openDeposit} className="mt-5 w-full rounded-2xl bg-white px-4 py-3 text-sm font-bold text-black transition hover:bg-cyan-100">+ شارژ حساب</button></section>
 <div className="mt-7 flex items-end justify-between"><div><p className="text-xs font-bold tracking-[.18em] text-cyan-300/60">سرویس‌ها</p><h2 className="mt-1 text-2xl font-black">انتخاب سرویس</h2></div><span className="text-xs text-white/35">{fa(services.length)} سرویس فعال</span></div>
 <section className="mt-4 space-y-3">{services.map(s=><div key={s.id}><div className="mb-2 flex items-center gap-2 text-xs text-white/40"><span>{s.icon==='apple'?'':'◈'}</span><span>{s.title}</span></div>{products.filter(p=>p.serviceId===s.id).map(p=><article key={p.id} className="group rounded-[28px] border border-white/10 bg-white/[.045] p-4 transition duration-300 hover:-translate-y-0.5 hover:border-cyan-300/20"><div className="flex items-center gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-white/10 text-2xl">{p.icon==='apple'?'':'◈'}</div><div className="min-w-0 flex-1"><h3 className="font-bold">{p.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-white/45">{p.description}</p></div><div className="text-left"><p className="text-sm font-black">{p.price} {p.currency}</p><button disabled={buying} onClick={()=>buy(p)} className="mt-2 rounded-xl bg-cyan-300 px-3 py-2 text-xs font-bold text-black disabled:opacity-50">{buying?'…':'خرید و شروع'}</button></div></div></article>)}</div>)}</section>
 <section className="mt-7 grid grid-cols-2 gap-3">{[['✓','راهنمای مرحله‌به‌مرحله'],['⚡','پشتیبانی سریع'],['🔒','پرداخت امن'],['◎','قیمت شفاف']].map(([i,t])=><div key={t} className="rounded-2xl border border-white/8 bg-white/[.035] p-4"><span className="text-lg">{i}</span><p className="mt-2 text-xs font-semibold text-white/65">{t}</p></div>)}</section>
 {message&&<button onClick={()=>setMessage('')} className="fixed bottom-20 left-1/2 z-[80] -translate-x-1/2 max-w-[90vw] rounded-2xl border border-cyan-300/20 bg-[#182235] px-4 py-3 text-xs text-white shadow-2xl">{message}</button>}
 </div><nav className="fixed bottom-3 left-1/2 z-40 flex w-[calc(100%-24px)] max-w-md -translate-x-1/2 justify-around rounded-3xl border border-white/10 bg-[#111827]/90 p-2 shadow-2xl backdrop-blur-2xl"><span className="rounded-2xl bg-white/10 px-5 py-2.5 text-xs font-bold">خانه</span><span className="px-5 py-2.5 text-xs text-white/40">سفارش‌ها</span><span onClick={openDeposit} className="cursor-pointer px-5 py-2.5 text-xs text-white/40">کیف پول</span><span onClick={()=>setMenu(true)} className="cursor-pointer px-5 py-2.5 text-xs text-white/40">پروفایل</span></nav>

 {deposit&&<div className="fixed inset-0 z-[70] overflow-y-auto bg-[#050812]/90 p-3 backdrop-blur-md"><div className="mx-auto flex min-h-full max-w-xl items-center py-6"><div className="w-full rounded-[32px] border border-white/10 bg-[#111827] p-5 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold tracking-[.2em] text-cyan-300/60">کیف پول</p><h2 className="mt-1 text-xl font-black">شارژ حساب</h2></div><button disabled={submittingDeposit} onClick={closeDeposit} className="rounded-xl bg-white/10 px-3 py-2 disabled:opacity-40">×</button></div>
 {depositStep==='method'&&<><p className="mt-6 text-sm text-white/50">روش پرداخت و مبلغ موردنظر برای شارژ را انتخاب کنید.</p><div className="mt-4 space-y-3"><button type="button" onClick={()=>{const c=cardMethods[0];if(c)setMethod(c.id)}} disabled={!cardMethods.length} className={`w-full rounded-2xl border p-4 text-right transition ${selectedMethod?'border-cyan-300/60 bg-cyan-300/10':'border-white/10 bg-white/5'} disabled:cursor-not-allowed disabled:opacity-40`}><div className="flex items-center justify-between"><div><p className="font-bold">کارت به کارت</p><p className="mt-1 text-xs text-white/40">انتقال بانکی و ارسال تصویر فیش</p></div><span className={`h-5 w-5 rounded-full border-2 ${selectedMethod?'border-cyan-300 bg-cyan-300':'border-white/20'}`}/></div></button><button type="button" disabled className="w-full cursor-not-allowed rounded-2xl border border-white/5 bg-white/[.02] p-4 text-right opacity-45"><p className="font-bold">پرداخت آنلاین</p><p className="mt-1 text-xs">به‌زودی فعال می‌شود</p></button></div><label className="mt-5 block text-xs font-semibold text-white/50">مبلغ شارژ</label><input inputMode="decimal" value={amount} onChange={e=>onAmount(e.target.value)} placeholder="مثلاً ۵۰۰۰۰۰" className="mt-2 w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-left outline-none focus:border-cyan-300/40"/><p className="mt-2 text-[11px] text-white/30">مبلغ به واحد موجودی سیستم ثبت می‌شود.</p><button type="button" disabled={!canContinue} onClick={()=>setDepositStep('receipt')} className="mt-5 w-full rounded-2xl bg-cyan-300 px-4 py-3 text-sm font-black text-black transition enabled:hover:bg-cyan-200 disabled:cursor-not-allowed disabled:opacity-30">ادامه</button></>}
 {depositStep==='receipt'&&<form onSubmit={submitDeposit}><div className="mt-6 rounded-2xl border border-cyan-300/10 bg-cyan-300/5 p-4"><p className="text-xs text-white/45">مبلغ انتخاب‌شده</p><p className="mt-1 text-xl font-black">{fa(numericAmount)} {wallet?.currency??'USD'}</p></div><p className="mt-5 text-sm leading-6 text-white/50">مبلغ را به یکی از کارت‌های زیر واریز کنید و سپس تصویر فیش را ارسال کنید.</p><div className="mt-4 space-y-2">{cardMethods.map(c=><div key={c.id} className={`rounded-2xl border p-4 ${c.id===selectedMethod?.id?'border-cyan-300/30 bg-cyan-300/5':'border-white/10 bg-white/5'}`}><div className="flex items-center justify-between"><p className="font-bold">{c.bankName??'بانک'}</p>{c.id===selectedMethod?.id&&<span className="text-xs text-cyan-300">انتخاب شده</span>}</div><p dir="ltr" className="mt-2 text-lg font-black tracking-wider text-right">{c.cardNumber}</p><p className="mt-1 text-xs text-white/45">به نام {c.holderName}</p></div>)}</div><label className="mt-5 block text-xs font-semibold text-white/50">فیش واریزی</label><input required type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setReceipt(e.target.files?.[0]??null)} className="mt-2 w-full rounded-2xl border border-dashed border-white/15 bg-white/5 p-4 text-xs file:ml-3 file:rounded-lg file:border-0 file:bg-white/10 file:px-3 file:py-2 file:text-white"/><p className="mt-2 text-[11px] text-white/30">فرمت‌های مجاز: JPG، PNG، WEBP یا PDF</p><button type="submit" disabled={!receipt||submittingDeposit} className="mt-5 w-full rounded-2xl bg-cyan-300 px-4 py-3 text-sm font-black text-black disabled:cursor-not-allowed disabled:opacity-30">{submittingDeposit?'در حال ارسال…':'ثبت فیش و ارسال برای بررسی'}</button><button type="button" disabled={submittingDeposit} onClick={()=>setDepositStep('method')} className="mt-2 w-full rounded-2xl bg-white/5 px-4 py-3 text-sm disabled:opacity-30">مرحله قبل</button></form>}
 {depositStep==='success'&&<div className="py-10 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-400/15 text-3xl text-emerald-300">✓</div><h3 className="mt-5 text-xl font-black">درخواست شارژ ثبت شد</h3><p className="mt-3 text-sm leading-7 text-white/50">فیش شما برای بررسی ادمین ارسال شد. پس از تأیید، حساب شما حداکثر تا ۳۰ دقیقه شارژ می‌شود و نتیجه برای شما ارسال خواهد شد.</p><button onClick={closeDeposit} className="mt-6 w-full rounded-2xl bg-white px-4 py-3 text-sm font-bold text-black">متوجه شدم</button></div>}
 </div></div></div>}

 {guide&&current&&<div className="fixed inset-0 z-[60] overflow-y-auto bg-[#050812]/90 p-3 backdrop-blur-md"><div className="mx-auto flex min-h-full max-w-xl items-center py-6"><div className="w-full rounded-[32px] border border-white/10 bg-[#111827] p-5 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold tracking-[.2em] text-cyan-300/60">فعال‌سازی</p><h2 className="mt-1 text-xl font-black">{guide.guide.title}</h2></div><button onClick={()=>setGuide(null)} className="rounded-xl bg-white/10 px-3 py-2">×</button></div><div className="mt-5"><div className="mb-2 flex justify-between text-[11px] text-white/40"><span>مرحله {fa(step+1)} از {fa(guide.steps.length)}</span><span>{fa(progressPct)}٪</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-cyan-300 transition-all duration-500" style={{width:`${progressPct}%`}}/></div></div><div className="mt-7"><div className="mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-cyan-300/10 text-2xl">{fa(step+1)}</div><h3 className="text-2xl font-black">{current.title}</h3><p className="mt-4 whitespace-pre-line text-sm leading-7 text-white/60">{current.content}</p>{current.imageUrl&&<img src={current.imageUrl} alt="" className="mt-5 max-h-56 w-full rounded-2xl object-cover"/>}{current.requiresInput&&current.inputKey&&<div className="mt-5"><label className="mb-2 block text-xs font-semibold text-white/50">{current.inputLabel??current.inputKey}</label><input value={input} onChange={e=>setInput(e.target.value)} className="w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 outline-none focus:border-cyan-300/40"/></div>}</div><div className="mt-8 flex gap-3"><button disabled={step===0||savingStep} onClick={()=>saveProgress(step-1)} className="flex-1 rounded-2xl bg-white/5 px-4 py-3 text-sm disabled:opacity-30">قبلی</button><button disabled={savingStep} onClick={async()=>{if(step===guide.steps.length-1){await saveProgress(step);setGuide(null)}else await saveProgress(step+1)}} className="flex-1 rounded-2xl bg-cyan-300 px-4 py-3 text-sm font-black text-black disabled:opacity-40">{savingStep?'در حال ذخیره…':step===guide.steps.length-1?'پایان':'بعدی'}</button></div></div></div></div>}
 </main>;
}
